services:
  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: adminexpress
      ME_CONFIG_BASICAUTH_PASSWORD: adminexpress
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - api-network

  mongo:
    image: mongo:8.0.4
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: 'gps_database'
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    #volumes:
    #  - ./MongoDB:/data/db
    networks:
      - api-network

  api:
    container_name: gpsapi
    build:
      context: .
    environment:
      MONGODB_URL: 'mongodb://mongo:27017'
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - api-network
    links:
      - mongo
    ports:
      - '5098:8080'

networks: 
    api-network:
      driver: bridge